#!/bin/bash

#see skript trükib välja kasutajanime ja kausta asukoha
#muutujale ipa omistame oma ip-aadress
ipa=`hostname -I`
echo -n "Sinu kasutajanimi on: "
whoami
sleep 0.5
echo -n "Sinu praegune kataloog on: " 
pwd
sleep 0.5
echo "Sinu arvuti ip aadress on: $ipa"
sleep 1.5
clear
