#!/bin/bash

#skript arvutab sisestatud arvude summa 

echo -n "Sisesta suvaline taisarv: "
read arv 
vastus=$arv
summa=0
while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "Arvu $vastus numbrite summa on $summa"
