#!/bin/bash

#skript loeb sisestatud numbri ning valjastab vastava kuu nime

echo -n "Sisesta kuu number: "
read number

if ((number >= 1 && kuu <= 12)); then
	case $number in
		1)echo "Jaanuar";;
		2)echo "Veebruar";;
		3)echo "Marts";;
		4)echo "Aprill";;
		5)echo "Mai";;
		6)echo "Juuni";;
		7)echo "Juuli";;
		8)echo "August";;
		9)echo "September";;
		10)echo "Oktoober";;
		11)echo "November";;
		12)echo "Detsember";;
	esac
else
	echo "Number ei sobi"
fi
