#!/bin/bash
#Skript ütleb kes valiti presidendiks 2016 aastal

aasta=2016
president="Kersti Kaljulaid"
lause_keskosa=". aastal valiti Eesti presidendiks "
lause="$aasta$lause_keskosa$president"
echo $lause
