#!/bin/bash

#skript kontrollib kas ar on paaris voi paaritu

echo -n "Sisesta suvaline taisarv: "
read arv

#arvutame jaagi jagades kahega

jaak=$(( $arv % 2 ))

if [ $jaak -eq 0 ]
then
	echo "$arv on paaris"
else
	echo "$arv on paaritu"
fi
