#!/bin/bash

#arvutab palju rahvast mahub bussidele

echo -n "Sisesta reisijate arv: "
read reisijad

echo -n "Sisesta kohtade arv bussis: "
read kohtade_arv

bussid=$(( $reisijad / $kohtade_arv ))

mahajaanud=$(( $reisijad % $kohtade_arv ))

if [ $mahajaanud  -eq 0 ]
then
	echo "Lisabusse pole tarvis"
else
	bussid=$(($bussid + 1 ))
fi

echo "Tarvis on $bussid bussi"
